# Generated by Django 5.1.7 on 2025-04-02 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(db_column='Author_id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(db_column='Isbn', max_length=13, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookLoans',
            fields=[
                ('loan_id', models.AutoField(db_column='Loan_id', primary_key=True, serialize=False)),
                ('date_out', models.DateTimeField(blank=True, db_column='Date_out', null=True)),
                ('due_date', models.DateTimeField(blank=True, db_column='Due_date', null=True)),
                ('date_in', models.DateTimeField(blank=True, db_column='Date_in', null=True)),
            ],
            options={
                'db_table': 'book_loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('card_id', models.CharField(db_column='Card_id', max_length=10, primary_key=True, serialize=False)),
                ('ssn', models.CharField(blank=True, db_column='Ssn', max_length=11, null=True, unique=True)),
                ('bname', models.TextField(blank=True, db_column='Bname', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
            ],
            options={
                'db_table': 'borrower',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('author', models.OneToOneField(db_column='Author_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='library_app.authors')),
            ],
            options={
                'db_table': 'book_authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('loan', models.OneToOneField(db_column='Loan_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='library_app.bookloans')),
                ('fine_amt', models.DecimalField(blank=True, db_column='Fine_amt', decimal_places=2, max_digits=5, null=True)),
                ('paid', models.IntegerField(blank=True, db_column='Paid', null=True)),
            ],
            options={
                'db_table': 'fines',
                'managed': False,
            },
        ),
    ]
