# Generated by Django 5.1.7 on 2025-04-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookauthors',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookloans',
            options={},
        ),
        migrations.AlterModelOptions(
            name='borrower',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fines',
            options={},
        ),
    ]
